language: python

sudo: required
dist: xenial # no 3.7 on 14.04 Trusty

python:
  - 3.7

# command to install dependencies
install:
  - pip install -e .

# command to run tests + coverage
script:
  - pytest --cov=sodinn -v
